### ISSUE TITLE
[Errno 13] Permission Denied

### ISSUE THREAD

**Issue by Kimi71Jedidiah** [Stephenfang51/VOC_to_COCO#12]
Traceback (most recent call last):
  File "voc_to_coco.py", line 65, in <module>
    mkdir(coco_path)
  File "voc_to_coco.py", line 54, in mkdir
    os.makedirs(path)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/VOC2020_COCO/'

Firstly, I thought it may be the setting of Big Sur SIP. But after I change the setting on macOS or turning to other Operation System, the problem still exists.

**Comment by 1phil1** [comment]
the Relative path of the "voc_annotations" should be modified to absolute path. And then the problem can be solved.
