### ISSUE TITLE
ValueError: Filename  is supposed to be an integer.

### ISSUE THREAD

**Issue by li-source** [Stephenfang51/VOC_to_COCO#8]
***************************[ Done ! Go check your file ]****************************
Traceback (most recent call last):
  File "/home/litong/voc_to_coco/VOC_to_COCO/voc_to_coco.py", line 166, in get_filename_as_int
    return int(filename)
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/litong/voc_to_coco/VOC_to_COCO/voc_to_coco.py", line 266, in <module>
    convert(xml_val_files, coco_json_annotations + 'val2017.json')
  File "/home/litong/voc_to_coco/VOC_to_COCO/voc_to_coco.py", line 209, in convert
    image_id = get_filename_as_int(filename)
  File "/home/litong/voc_to_coco/VOC_to_COCO/voc_to_coco.py", line 168, in get_filename_as_int
    raise ValueError("Filename %s is supposed to be an integer." % (filename))
ValueError: Filename  is supposed to be an integer.

Process finished with exit code 1

**Comment by StephenZhao1** [comment]
我也是同样的错误，是不是这个只能支持那种000001.jpg这样子名称的数据集

**Comment by PrakharPrashantSingh** [comment]
same error.. any solution??

**Comment by ShuShuai163** [comment]
get_filename_as_int，因为这一句，所以图片名字只能是数字
